Feature/authorization
naturalnumber/Revitalize pull request #2
Opened 2020-02-09 19:48 UTC by naturalnumber

Merging work so far

2020-02-09 20:20 UTC, lmsch requested changes

2020-02-09 20:20 UTC, LMSkippy commented on backend_api/urls.py
> +        path('revitalize/', include('Revitalize.urls')),
Can we change the endpoints from revitalize/ to api/

2020-02-10 02:32 UTC, naturalnumber commented on backend_api/urls.py
> +        path('revitalize/', include('Revitalize.urls')),
sure

2020-02-10 02:33 UTC, naturalnumber commented on backend_api/urls.py
> +        path('revitalize/', include('Revitalize.urls')),
Can I do it for the next pull request, which will be immediately after this is accepted

2020-02-10 02:52 UTC, LMSkippy commented on backend_api/urls.py
> +        path('revitalize/', include('Revitalize.urls')),
It does yes.

2020-02-10 02:54 UTC, lmsch approved these changes

2020-02-10 14:25 UTC, MatthewBowlan approved these changes

2020-02-11 15:35 UTC, merged