Feature/authorization
naturalnumber/Revitalize pull request #3
Opened 2020-02-26 04:34 UTC by naturalnumber

Pull request to bring dev up to the current functionality

2020-03-02 17:27 UTC, MatthewBowlan submitted a review, later dismissed

2020-03-02 19:40 UTC, lmsch requested changes

2020-03-02 19:40 UTC, LMSkippy commented on backend_api/settings.py
> +CORS_ORIGIN_ALLOW_ALL = True
Probably should revert this back to whitelist.

2020-03-02 19:47 UTC, naturalnumber commented on backend_api/settings.py
> +CORS_ORIGIN_ALLOW_ALL = True
Oops

2020-03-02 21:05 UTC, lmsch submitted a review, later dismissed

2020-03-04 15:07 UTC, MatthewBowlan submitted a review, later dismissed

2020-04-01 03:13 UTC, merged